djangoapp/blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/", views.post, name="post"),
    path("page/", views.page, name="page"),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from utils.rands import slugify_new


# Create your models here.
class Tag(models.Model):
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    name = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=100,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=100,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Page(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=100,
    )
    is_published = models.BooleanField(
        default=False,
        help_text="Este campo precisara estar marcado para a página ser exibida publicamente",
    )
    content = models.TextField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Post(models.Model):
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    title = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True,
        default=None,
        null=True,
        blank=True,
        max_length=100,
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text="Este campo precisara estar marcado para a página ser exibida publicamente",
    )
    content = models.TextField()
    cover = models.ImageField(upload_to="posts/%Y/%m/", blank=True, default="")
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text="Se marcado, a imagem de capa sera exibida no conteudo do post",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="post_created_by",
    )
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="post_updated_by",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        default=None,
    )
    tags = models.ManyToManyField(Tag, blank=True, default="")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)
        return super().save(*args, **kwargs)

djangoapp/site_setup/models.py
from django.db import models
from utils.images import resize_image
from utils.model_validators import validate_png


class MenuLink(models.Model):
    class Meta:
        verbose_name = "Menu Link"
        verbose_name_plural = "Menu Links"

    text = models.CharField(max_length=50)
    url_or_path = models.CharField(max_length=2048)
    new_tab = models.BooleanField(default=False)
    site_setup = models.ForeignKey(
        "SiteSetup",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
    )

    def __str__(self):
        return self.text


class SiteSetup(models.Model):
    class Meta:
        verbose_name = "Setup"
        verbose_name_plural = "Setup"

    title = models.CharField(max_length=65)
    description = models.CharField(max_length=255)

    show_header = models.BooleanField(default=True)
    show_search = models.BooleanField(default=True)
    show_menu = models.BooleanField(default=True)
    show_description = models.BooleanField(default=True)
    show_pagination = models.BooleanField(default=True)
    show_footer = models.BooleanField(default=True)

    favicon = models.ImageField(
        upload_to="assets/favicon/%Y/%m/",
        blank=True,
        default="",
        validators=[validate_png],
    )

    def save(self, *args, **kwargs):
        current_favicon_name = str(self.favicon.name)
        super().save(*args, **kwargs)
        favicon_changed = False

        if self.favicon:
            favicon_changed = current_favicon_name != self.favicon.name

        if favicon_changed:
            resize_image(self.favicon, 32)

    def __str__(self):
        return self.title

djangoapp/blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

posts = list(range(1000))


def index(request):
    paginator = Paginator(posts, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "blog/pages/index.html",
        {
            "page_obj": page_obj,
        },
    )


def page(request):
    paginator = Paginator(posts, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "blog/pages/page.html",
        {
            # 'page_obj': page_obj,
        },
    )


def post(request):
    paginator = Paginator(posts, 9)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "blog/pages/post.html",
        {
            # 'page_obj': page_obj,
        },
    )

djangoapp/site_setup/views.py
from django.shortcuts import render

# Create your views here.

djangoapp/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  {% include 'blog/partials/_head.html' %}
</head>
<body>
  <div class="blog-wrapper">
    {% if site_setup.show_header %}
      {% include 'blog/partials/_header.html' %}
    {% endif %}

    {% block content %}{% endblock content %}
    
    {% if site_setup.show_pagination %}
      {% include 'blog/partials/_pagination.html' %}
    {% endif %}
    
    {% if site_setup.show_footer %}
      {% include 'blog/partials/_footer.html' %}
    {% endif %}
  </div>
</body>
</html>

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        <div class="card-grid">
          {% for i in ""|ljust:"9" %}
            {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
          {% endfor %}
        </div>

      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">A page 😍</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium 
          eaque placeat, optio architecto dignissimos est iure ipsum, iste doloribus dolorum 
          nostrum veniam aspernatur adipisci eos et ab facilis, fugit labore!
        </p>
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">
      <div class="single-post-cover pb-base">
        <img loading="lazy" src="https://picsum.photos/1920/1080/?rand=12" alt="Change me">
      </div>

      <h2 class="single-post-title pb-base center">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-user"></i>
            <span>
              Author Full Name
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              20/04/2023
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-tag"></i>
            <span>
              Categoria
            </span>
          </a>
        </div>
      </div>

      <p class="single-post-excerpt pb-base">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore, vero
        fugiat eum perferendis accusamus enim quos obcaecati. Voluptates a vel
        obcaecati ipsa in dignissimos facere odio et, ab provident assumenda!
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {% include 'blog/partials/_temp.html' %} 
      
        <div class="post-tags">
          <span>Tags: </span>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Testando</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Atenção</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Obrigado</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Educação</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Python</span>
          </a>

        </div>
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}

djangoapp/blog/templates/blog/partials/_footer.html
<footer class="footer section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">
      <div class="center">
        <a href="#"> © {% now "Y" %} {{ site_setup.title }} - Todos os direitos reservados. </a>
      </div>
    </div>
  </div>
</footer>

djangoapp/blog/templates/blog/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'blog/css/remedy.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

{% if site_setup.favicon %}
  <link rel="shortcut icon" href="{{ site_setup.favicon.url }}" type="image/png">
{% endif %}

<title>{{ site_setup.title }}</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

djangoapp/blog/templates/blog/partials/_header.html
<header class="header section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">

      <h1 class="blog-title center pb-base">
        <a class="blog-link" href="/">{{ site_setup.title }}</a>
      </h1>
      
      {% if site_setup.show_description %}
        <p class="blog-description pb-base center">
          {{ site_setup.description }}
        </p>
      {% endif %}

      {% if site_setup.show_search %}
        <div class="search pb-base center">
          <form class="search-form" action="#" method="get">
            <div class="search-content">
              <label class="sr-only" id="search-label" for="search-input">Search</label>
              <input
                class="search-input"
                type="search"
                name="search"
                id="search-input"
                placeholder="Search"
                value="Non risu potius quam oratione eiciendum? Quo pleb "
              >
              <button class="search-btn" type="submit" aria-labelledby="search-label">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </form>
        </div>
      {% endif %}

      {% if site_setup.show_menu %}
        <nav class="menu">
          <ul class="menu-items">
            {% for link in site_setup.menulink_set.all %}
              <li class="menu-item">
                {% if link.new_tab %}
                  <a target="_blank" class="menu-link" href="{{ link.url_or_path}}">{{ link.text }}</a>
                {% else %}
                  <a class="menu-link" href="{{ link.url_or_path}}">{{ link.text }}</a>
                {% endif %}
              </li>
            {% endfor %}
          </ul>
        </nav>
      {% endif %}
      
    </div>
  </div>
</header>

djangoapp/blog/templates/blog/partials/_pagination.html
{% if page_obj and page_obj.has_other_pages %}

<div class="separator"></div>

<div class="pagination-wrapper section-wrapper">
  <div class="pagination-content section-content-wide">
    <div class="pagination-gap section-gap">

      <nav class="pagination-links" aria-label="Pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
              <a title="Page 1" aria-label="Page 1" href="?page=1{{ search_url }}">
                  <i class="fa-solid fa-backward-fast"></i>
              </a>
              <a title="Page {{ page_obj.previous_page_number }}" aria-label="Page {{ page_obj.previous_page_number }}" href="?page={{ page_obj.previous_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-left"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}

            <span class="current" title="Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}" aria-current="page">
              {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
              <a title="Page {{ page_obj.next_page_number }}" aria-label="Page {{ page_obj.next_page_number }}" href="?page={{ page_obj.next_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-right"></i>
              </a>
              <a title="Page {{ page_obj.paginator.num_pages }}" aria-label="Page {{ page_obj.paginator.num_pages }}" href="?page={{ page_obj.paginator.num_pages }}{{ search_url }}">
                <i class="fa-solid fa-forward-fast"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}
        </span>
      </nav>
      
    </div>
  </div>
</div>

{% endif %}

djangoapp/blog/templates/blog/partials/_post-card.html
<article class="card">
  
  <div class="card-cover-wrapper">
    <a href="#" class="card-cover-link">
      <img 
        class="card-cover"
        loading="lazy"
        src="https://picsum.photos/745/419/?rand=2{{ i }}" 
        alt="Change me"
      >
    </a>
  </div>

  <div class="card-text-wrapper">
    <div class="card-title-wrapper">
      <h2 class="card-title">
        <a href="#" class="card-title-link">
          Lorem ipsum dolor sit amet.
        </a>
      </h2>
    </div>

    <div class="card-content-wrapper">
      <p class="card-content">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur nulla omnis, 
        maiores tempore pariatur a obcaecati atque deserunt reiciendis quam! 
      </p>

      <div class="card-actions">
        <a class="card-action-link" href="#">
          <span>Read</span>
          <i class="fa-solid fa-circle-arrow-right"></i>
        </a>
      </div>
    </div>
  </div>

</article>